---
title: "Grade_Analysis_SL"
author: "Sami Louahlia"
format: html
code-fold: true
---
```{r}
#|message: false
here::i_am("r-101-grade-analysis.Rproj")
library(here)
library(vroom)
library(dplyr)
library(tidyr)
library(ggplot2)
```

### Q1 Data
```{r}
#|message: false
grade <- vroom(here("grades.csv"))
```
### Q2 
```{r}
Q2 <- grade |> summarize("minimum" = min(Exam, na.rm=TRUE), "maxixmum" = max(Exam, na.rm=TRUE), "median" = median(Exam, na.rm=TRUE), "mean" = mean(Exam, na.rm=TRUE))

table2 <- knitr::kable(Q2)
```
This table offers descriptive of the variable Exam
`r table2`

### Q3 
```{r}
NoFinal <- grade |> filter(is.na(Exam)==TRUE)
NoFinalnb <- count(NoFinal)
```
A total of `r NoFinalnb` students did not take the final exam.

### Q4 
```{r}
GradeB <- grade |> filter(!is.na(Exam))
ggplot(GradeB, aes(x = Exam))+
  geom_bar()

```

### Q5 
```{r}
grouped_grade <- grade|> group_by(Group)
 countpergroup <- count(grouped_grade)
 table5<- knitr::kable(countpergroup)
```
This table shows how many people can be found in each groups (here called grp)
`r table5`

### Q6
```{r}
ggplot(grade, aes(x=Group))+
  geom_bar()
```
Here is a graphical representation of the group's number of members.


